CC := gcc
client := client2.c
server := server2.c
myserver := server3.c
myclient := client.c
all: 
	$(CC) -o client $(client)
	$(CC) -o server $(server)
	$(CC) -o myserver $(myserver)
	$(CC) -o myclient $(myclient)
clean:
	rm client server myserver myclient
